### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by Lenni009** [NMSCD/CommunityMission-Progress-Viewer#2]
The page displays "Invalid Date" in a lot of places:

1. go to https://community-mission.nmscd.com
2. Under `Options`, click on the right icon to get a summary of irregularities
3. All the dates are invalid

**Comment by Khaoz-Topsy** [comment]
Great, another breaks in one browser and not the other 😂. I wonder if this is from me updating the dependencies or if it has been like this for a while 🤔

**Comment by Lenni009** [comment]
Why do we need that dayjs lib anyway? Can the native browser date API not do something this lib can?

**Comment by Lenni009** [comment]
There's also some invalid dates on Chrome, but there's more of them on Firefox.

If I know the requirements I could probably write up some code for time formatting which you could then implement here. Or maybe I can even fix the bug myself in the code, but I need to know what the expected format and the original purpose of this dayjs library is.

**Comment by Khaoz-Topsy** [comment]
Interesting, I don't see any invalid dates in chrome 
![image](https://github.com/NMSCD/CommunityMission-Progress-Viewer/assets/15005470/2e286cd8-3242-499c-979e-ae39db5c56ec)

The date format (in the incident section) is dependent on whether or not there should be a time displayed. So either a long time (YYYY-MM-DD HH:mm) if the time is known or just a short date (YYYY-MM-DD) if it was a whole day issue. In other places the date format is different, just because of limited space 😅. I am pretty sure that I used dayJS just because I was lazy, looks like only the formatDate, addDays and dateIsBefore functions are used. So if you rewrite them (in the `helper/dateHelper.ts` file), then dayJS can easily be removed 😋

I think the bug comes from the `.toLocaleString()` method. I used it to represent the UTC date from the back-end into time that is in the user's timezone. Your system's date format is probably different to mine, which is probably slightly different between Chrome and Firefox 🤔

**Comment by Lenni009** [comment]
Maybe because our browsers are set to different languages. Testing this stuff is really hard, since it can work fine in one language, but break for another (like in this case, or for the UD22 website I made last year)
![grafik](https://github.com/NMSCD/CommunityMission-Progress-Viewer/assets/91371655/5986b59c-8cbb-481b-b624-770bb6af9ec5)

**Comment by Khaoz-Topsy** [comment]
Yeah, I need to move away from parsing the dates 🤔. It was just so much easier to read than using the Date.UTC() 😅

**Comment by Khaoz-Topsy** [comment]
And this is probably not helping 😂

![image](https://github.com/NMSCD/CommunityMission-Progress-Viewer/assets/15005470/e061e4af-058c-45fd-8650-72eceefc2800)
